### ISSUE TITLE
some random issue

### ISSUE THREAD

**Issue by WeiningLi** [WeiningLi/card-forum#7]
Beautifully styled description of this random model 

---
Model fact sheet 

```yaml
link: ...
architecture: detectron2..
doctype: scientific..
description: ..
config-names:
- lp-model-name: lp://PubLayNet/model1/xxx
   architecture: detectron2
   sizes: small
- lp-model-name: lp://PubLayNet/model2/xxx
   architecture: efficiendet
   sizes: large
```
